# Generated by Django 4.2 on 2023-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnarecord',
            name='citable',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tnarecord',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tnarecord',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tnarecord',
            name='tna_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
