# Generated by Django 4.2 on 2023-04-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_tnarecord_citable_alter_tnarecord_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnarecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='tnarecord',
            name='tna_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
